Downgrade yarl<1.2
Getting this error?

```
TypeError: Inheritance a class <class 'aiohttp.http_writer.URL'> from URL is forbidden
```

This is due to yarl 1.2 having a breaking change that breaks aiohttp. Downgrade
your yarl using `pip install -U "yarl<1.2"`